[package]
name = "strudel"
version = "0.1.0"
homepage = "https://github.com/56quarters/strudel"
repository = "https://github.com/56quarters/strudel"
license = "GPL-3.0+"
edition = "2021"

[dependencies]
clap = { version = "3.0.0-rc.8", features = ["cargo", "derive", "std"], default-features = false }
futures-util = "0.3.17"
rppal = "0.13.1"
hyper = { version = "0.14.16", features = ["full"] }
tokio = { version = "1.14.0", features = ["full"] }
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
prometheus = { version = "0.13.0", features = ["process"] }
tracing = "0.1.11"
tracing-subscriber = "0.1.6"

[lib]
name = "strudel"
path = "src/strudel/lib.rs"